services:
  # no service
  initializer:
    image: alpine
    container_name: ${NETWORK_INIT_CONTAINER_NAME:-ats-init-network}
    networks:
      - ats_internal_network
      - ats_vault_network
      - ats_monitoring_network
      - ats_external_network
      - ats_gateway_network

networks:
  ats_internal_network:
    driver: bridge
    internal: ${INTERNAL_NETWORK_IS_INTERNAL:-true}
    name: ${INTERNAL_NETWORK_NAME:-ats-internal-network}
  ats_vault_network:
    driver: bridge
    internal: ${VAULT_NETWORK_IS_INTERNAL:-true}
    name: ${VAULT_NETWORK_NAME:-ats-vault-network}
  ats_monitoring_network:
    driver: bridge
    internal: ${MONITORING_NETWORK_IS_INTERNAL:-false}
    name: ${MONITORING_NETWORK_NAME:-ats-monitoring-network}
  ats_external_network:
    driver: bridge
    internal: false
    name: ${EXTERNAL_NETWORK_NAME:-ats-external-network}
  ats_gateway_network:
    driver: bridge
    internal: false
    name: ${GATEWAY_NETWORK_NAME:-ats-gateway-network}
