services:
  # dns
  dns:
    build:
      context: .
      dockerfile: ./dns_conf/Dockerfile
    container_name: ${DNS_CONTAINER_NAME:-ats-dns}
    environment:
      - COREDNS_PORT=53
      - DOMAIN=${DNS_HOST_NAME:-dns.ats.internal}
    networks:
      ats_internal_network:
        aliases:
          - dns
    volumes:
      - ${DNS_CORE_FILE_PATH:-./dns/Corefile}:/etc/coredns/Corefile:ro
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    restart: always

networks:
  ats_internal_network:
    external: true
    name: ${INTERNAL_NETWORK_NAME:-ats-internal-network}