services:
  vault:
    build:
      context: .
      dockerfile: ./vault/Dockerfile
    container_name: ${VAULT_CONTAINER_NAME:-ats-vault}
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    ports:
      - "${VAULT_PORT:-8200}:8200"
    volumes:
      - ./vault/config:/vault/config:ro
      - ${VAULT_LOG_PATH:-./logs/vault}:/vault/logs
      - ats-vault-data:/vault/data
      - ats-vault-logs:/vault/logs
      - ats-vault-init-keys:/vault/init-keys
    networks:
      - ats_internal_network
      - ats_vault_network
    dns:
      - ${CUSTOM_DNS_IP}

networks:
  ats_internal_network:
    external: true
    name: ${INTERNAL_NETWORK_NAME:-ats-internal-network}
  ats_vault_network:
    external: true
    name: ${VAULT_NETWORK_NAME:-ats-vault-network}

volumes:
  ats-vault-data:
    external: false
    name: ${VAULT_DATA_VOLUME_NAME:-ats-vault-data}
  ats-vault-logs:
    external: true
    name: ${VAULT_LOGS_VOLUME_NAME:-ats-vault-logs}
  ats-vault-init-keys:
    external: true
    name: ${VAULT_INIT_KEYS_VOLUME_NAME:-ats-vault-init-keys}
