services:
  session-cluster-redis:
    image: redis:latest
    container_name: session-cluster-redis
    command: [ "redis-server", "--port", "6379" ]
    networks:
      - ats_internal_network

  ats-user-db:
    build:
      context: .
      dockerfile: ./db_conf/user_db/Dockerfile
    container_name: ats-user-db
    environment:
      POSTGRES_USER: ${USER_DB_VAULT_ID:-user}
      POSTGRES_PASSWORD: ${USER_DB_VAULT_PW:-user123}
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - ${PG_DATA:-./pg_data}:/var/lib/postgresql/data
      - ${PG_USER_INIT:-./db_conf/user_db/init}:/docker-entrypoint-initdb.d
      - ${PG_HBA_CONF:-./db_conf/user_db/pg_hba.conf}:/var/lib/postgresql/data/pg_hba.conf
    networks:
      - ats_internal_network

networks:
  ats_internal_network:
    external: true
