services:
  session-cluster-redis:
    image: redis:latest
    restart: unless-stopped
    container_name: session-cluster-redis
    command: [ "redis-server", "--port", "6379" ]
    networks:
      - ats_internal_network

  ats-user-db:
    build:
      context: .
      dockerfile: ./db_conf/user_db/Dockerfile
      args:
        USER_DB_INIT_TEMPLATE_PATH: ${USER_DB_INIT_TEMPLATE_PATH:-./db_conf/user_db/templates}
        SSL_PATH_IN_CONTAINER: ${USER_DB_CERT_PATH_IN_CONTAINER:-/etc/ssl/certs}
    container_name: ${USER_DB_CONTAINER_NAME:-ats-user-db}
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      VAULT_USER_ID: ${USER_DB_VAULT_ID:-user}
      VAULT_USER_PW: ${USER_DB_VAULT_PW:-user123}
    ports:
      - "${USER_DB_PORT:-5432}:5432"
    volumes:
      - user_db_pg_data:/var/lib/postgresql/data
    networks:
      ats_internal_network:
        aliases:
          - ${USER_DB_HOST_NAME:-user-db.ats.internal}

networks:
  ats_internal_network:
    external: true
    name: ${INTERNAL_NETWORK_NAME:-ats-internal-network}

volumes:
  user_db_pg_data:
    external: true
    name: ${USER_DB_PG_DATA_VOLUME_NAME:-ats-user-db-pg-data}