services:
  ats-cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: ats-cadvisor
    ports:
      - "8080:8080"  # Expose cAdvisor on port 8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    networks:
      - ats_internal_network

  ats-prometheus:
    image: prom/prometheus:latest
    container_name: ats-prometheus
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - ats_internal_network
      - ats_monitoring_network

  ats-grafana:
    image: grafana/grafana:latest
    container_name: ats-grafana
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    environment:
      - ${GF_SECURITY_ADMIN_PASSWORD:-admin}
    networks:
      - ats_internal_network
      - ats_monitoring_network

  ats-otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    ports:
      - "4317:4317"
      - "55680:55680"
    volumes:
      - ./opentelemetry/otel-config.yml:/etc/otel/config.yml
    command: [ "--config", "/etc/otel/config.yml" ]
    networks:
      - ats_internal_network

networks:
  ats_internal_network:
    external: true
  ats_vault_network:
    external: true
  ats_monitoring_network:
    external: true
