services:
  ats-test-server-spring:
    image: aikusoni/ats-test-server-spring:latest
    container_name: ats-test-server-spring
    volumes:
      - ${TEST_SERVER_SPRING_LOG_HOME:-./logs/test}:/logs
    environment:
      LOG_HOME: logs
      SERVER_PORT: 8900
      SPRING_PROFILES_ACTIVE: local
    networks:
      - internal_network

  ats-session-auth-server:
    image: aikusoni/ats-session-auth-server:latest
    volumes:
      - ${SESSION_AUTH_SERVER_LOG_HOME:-./logs/session}:/logs
    environment:
      DB_USER: ${AUTH_DB_USER:-user}
      DB_PASSWORD: ${AUTH_DB_PASSWORD:-user123}
      DB_DRIVER_CLASS_NAME: ${AUTH_DB_DRIVER_CLASS_NAME:-org.postgresql.Driver}
      DB_URL: ${AUTH_DB_URL:-jdbc:postgresql://ats-user-db:5432/userdb}
      LOG_HOME: logs
      SERVER_PORT: 8000
      SPRING_PROFILES_ACTIVE: local
      REDIS_HOST: session-cluster-redis
      REDIS_PORT: 6379
    deploy:
      replicas: 2  # Number of replicas for scaling
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    depends_on:
      - session-cluster-redis
      - ats-user-db
    networks:
      - internal_network

  session-cluster-redis:
    image: redis:latest
    container_name: session-cluster-redis
    command: [ "redis-server", "--port", "6379" ]
    networks:
      - internal_network

  ats-user-db:
    image: postgres:latest
    container_name: ats-user-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - ${PG_DATA:-./pg_data}:/var/lib/postgresql/data
      - ${PG_USER_INIT:-./pg_user_init}:/docker-entrypoint-initdb.d
    networks:
      - internal_network

  ats-landing:
    image: aikusoni/ats-landing:latest
    container_name: ats-landing
    volumes:
      - frontend_landing_volume:/upload_target
    command: [ "/bin/sh", "-c", "cp -r /dist/* /upload_target/" ]

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ${NGINX_CONF:-./nginx/nginx.conf}:/etc/nginx/nginx.conf
      - ${NGINX_LOG_HOME:-./logs/nginx}:/var/log/nginx
      - frontend_landing_volume:/usr/share/nginx/html/landing
    depends_on:
      - ats-test-server-spring
      - ats-session-auth-server
    networks:
      - internal_network
      - external_network

networks:
  internal_network:
    driver: bridge
    internal: true
  external_network:
    driver: bridge

volumes:
  frontend_landing_volume:
    external: false
