services:
  ats-cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"  # Expose cAdvisor on port 8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    networks:
      - internal_network

  ats-prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - internal_network
      - external_network

  ats-grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    environment:
      - ${GF_SECURITY_ADMIN_PASSWORD:-admin}
    networks:
      - internal_network
      - external_network

  ats-otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    ports:
      - "4317:4317"
      - "55680:55680"
    volumes:
      - ./opentelemetry/otel-config.yaml:/etc/otel/config.yaml
    command: [ "--config", "/etc/otel/config.yaml" ]
    networks:
      - internal_network


networks:
  internal_network:
    driver: bridge
    internal: true  
  external_network:
    driver: bridge  
