version: '3.8'
services:
  ats-test-server-spring:
    image: aikusoni/ats-test-server-spring:latest
    container_name: ats-test-server-spring
    environment:
      LOG_HOME: logs
      SERVER_PORT: 8900
      SPRING_PROFILES_ACTIVE: local
    ports:
      - "8900:8900"
    networks:
      - internal_network

  ats-session-auth-server:
    image: aikusoni/ats-session-auth-server:latest
    container_name: ats-session-auth-server
    environment:
      DB_USER:
      DB_PASSWORD:
      DB_DRIVER_CLASS_NAME:
      DB_URL:
      LOG_HOME: logs
      SERVER_PORT: 8000
      SPRING_PROFILES_ACTIVE: local
    ports:
      - "8000:8000"
    networks:
      - internal_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ats-test-server-spring
      - ats-session-auth-server
    networks:
      - internal_network
      - external_network

networks:
  internal_network:
    driver: bridge
  external_network:
    driver: bridge
