version: '3.8'
services:
  ats-test-server-spring:
    image: aikusoni/ats-test-server-spring:latest
    container_name: ats-test-server-spring
    volumes:
      - ${TEST_SERVER_SPRING_LOG_HOME:-./logs/test}:/logs
    environment:
      LOG_HOME: logs
      SERVER_PORT: 8900
      SPRING_PROFILES_ACTIVE: local
    networks:
      - internal_network

  ats-session-auth-server:
    image: aikusoni/ats-session-auth-server:latest
    container_name: ats-session-auth-server
    volumes:
      - ${SESSION_AUTH_SERVER_LOG_HOME:-./logs/session}:/logs
    environment:
      DB_USER: ${AUTH_DB_USER:-sa}
      DB_PASSWORD: ${AUTH_DB_PASSWORD:-password}
      DB_DRIVER_CLASS_NAME: ${AUTH_DB_DRIVER_CLASS_NAME:-org.h2.Driver}
      DB_URL: ${AUTH_DB_URL:-jdbc:h2:mem:testdb}
      LOG_HOME: logs
      SERVER_PORT: 8000
      SPRING_PROFILES_ACTIVE: local
    networks:
      - internal_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${NGINX_LOG_HOME:-./logs/nginx}:/var/log/nginx
    depends_on:
      - ats-test-server-spring
      - ats-session-auth-server
    networks:
      - internal_network
      - external_network

networks:
  internal_network:
    driver: bridge
  external_network:
    driver: bridge
